#pragma config(Motor,  motor1,          leftmotor1,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          rightmotor1,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          leftmotor2,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          rightmotor2,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
startMotor(leftmotor1, 10);
startMotor(rightmotor1, 10);
startMotor(leftmotor2, 10);
startMotor(rightmotor2, 10);
stop;
while(1==1)

		{
			motor[leftmotor1] = vexRT[Ch3];
			motor[rightmotor1] = vexRT[Ch2];

			if(vexRT[Btn6U] == 1)
		{
			
			
		}

}
