#pragma config(Motor,  motor1,          leftmotor1,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          rightmotor1,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          leftmotor2,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          rightmotor2,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
// Starting up each of the motors
startMotor(leftmotor1, 10);
startMotor(rightmotor1, 10);
startMotor(leftmotor2, 10);
startMotor(rightmotor2, 10);
stop;

// While makes it run smoother	
	while(1==1)

		{
			motor[leftmotor1] = vexRT[Ch3];
			motor[rightmotor1] = vexRT[Ch2];
			//Connects controller joycons to each motor
			if(vexRT[Btn6U] == 1)
			// Also button connects to button?
		{
			
			
		}

}
